version: '2'

volumes:
  webroot:
    driver: local

services:
  app:
    build:
      context: ../../
      dockerfile: docker/release/Dockerfile
    links:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: todob.settings.release
      MYSQL_HOST: db
      MYSQL_USER: todo
      MYSQL_PASSWORD: password
      DEBUG: "true"
    volumes:
      - webroot:/var/www/todob
    command:
      - uwsgi
      - "--socket /var/www/todob/todob.sock"
      - "--chmod-socket=666"
      - "--module todob.wsgi"
      - "--master"
      - "--die-on-term"

  test:
    image: salle79/todobackend-specs
    links:
      - nginx
    environment:
      URL: http://nginx:8000/todos
      JUNIT_REPORT_PATH: /reports/acceptance.xml
      JUNIT_REPORT_STACK: 1
    command: --reporter mocha-jenkins-reporter

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    links:
      - app
    ports:
      - "8000:8000"
    volumes:
      - webroot:/var/www/todob

  db:
    image: mysql:5.6
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: todobackend
      MYSQL_USER: todo
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  agent:
    image: jmenga/ansible
    links:
      - db
    environment:
      PROBE_HOST: "db"
      PROBE_PORT: "3306"
    command: ["probe.yml"]